<?php

namespace NHSEngland;

class AcfFields implements \Dxw\Iguana\Registerable
{
    public function register()
    {
        add_action('init', [$this, 'addFields']);
    }

    public function addFields()
    {
        if (function_exists('acf_add_options_page')) {
            acf_add_options_page([
                'page_title' => 'Extra options',
                'menu_title' => 'Extra options',
                'parent_slug' => 'themes.php',
            ]);
        }

        if (function_exists('register_field_group')) {
            // Homepage Small Promo Boxes
            acf_add_local_field_group([
                'key' => 'group_58c29a7360fd3',
                'title' => 'Homepage Small Promo Boxes',
                'fields' => [
                    [
                        'key' => 'field_51ada3d8b7c31',
                        'label' => 'Small Promo Boxes',
                        'name' => 'small_promo_boxes',
                        'type' => 'repeater',
                        'instructions' => 'Small promotional boxes on the homepage under the larger promotional box. All 3 boxes should be completed.',
                        'sub_fields' => [
                            [
                                'default_value' => '',
                                'formatting' => 'none',
                                'key' => 'field_51ada406b7c32',
                                'label' => 'Title',
                                'name' => 'small_promo_title',
                                'type' => 'text',
                                'instructions' => 'Title for this promo box',
                                'column_width' => '',
                            ],
                            [
                                'default_value' => '',
                                'formatting' => 'html',
                                'key' => 'field_51ada415b7c33',
                                'label' => 'Body',
                                'name' => 'small_promo_body',
                                'type' => 'textarea',
                                'instructions' => 'Body copy for this promo box',
                                'column_width' => '',
                            ],
                            [
                                'post_type' => [
                                    0 => 'all',
                                ],
                                'multiple' => 0,
                                'allow_null' => 0,
                                'key' => 'field_51ada44eb7c34',
                                'label' => 'Link',
                                'name' => 'small_promo_link',
                                'type' => 'url',
                                'instructions' => 'Internal link for this promo box',
                                'column_width' => '',
                            ],
                        ],
                        'row_min' => 3,
                        'row_limit' => 3,
                        'layout' => 'table',
                        'button_label' => 'Add Row',
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'page_template',
                            'operator' => '==',
                            'value' => 'page-home.php',
                            'order_no' => 0,
                            'group_no' => 0,
                        ],
                    ],
                ],
                'options' => [
                    'position' => 'normal',
                    'layout' => 'default',
                    'hide_on_screen' => [],
                ],
                'menu_order' => 2,
            ]);

            // Replace Header Logo
            acf_add_local_field_group([
                'key' => 'group_57b572547381c',
                'title' => 'Replace Header Logo',
                'fields' => [
                    [
                        'key' => 'field_57b572c84b437',
                        'label' => 'Replace Header Logo',
                        'name' => 'replace_header_logo',
                        'type' => 'image',
                        'instructions' => 'White logo on transparent background, min 90px high',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'acf-options-extra-options',
                        ],
                    ],
                ],
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => 1,
                'description' => '',
            ]);

            // Sidebar Social Network Options
            acf_add_local_field_group([
                'key' => 'group_58c29b0db5682',
                'title' => 'Sidebar Social Network Options',
                'fields' => [
                    [
                        'default_value' => 1,
                        'message' => 'Show social networks',
                        'key' => 'field_51adc32669813',
                        'label' => 'Show Social Networks',
                        'name' => 'show_social_networks',
                        'type' => 'true_false',
                        'instructions' => 'Check to show the social network icons in the sidebar',
                    ],
                    [
                        'key' => 'field_51b04e32409c7',
                        'label' => 'Social Networks',
                        'name' => 'social_networks',
                        'type' => 'repeater',
                        'instructions' => 'Add as many social networks as you need, icons must be 24px square. Note, these links are for following purposes only, not to share content from this site to these networks.',
                        'sub_fields' => [
                            [
                                'default_value' => '',
                                'formatting' => 'none',
                                'key' => 'field_51b04e72409c8',
                                'label' => 'Network Name',
                                'name' => 'network_name',
                                'type' => 'text',
                                'instructions' => 'The name of the social network.',
                                'column_width' => '',
                            ],
                            [
                                'save_format' => 'url',
                                'preview_size' => 'full',
                                'library' => 'all',
                                'key' => 'field_51b04eab409c9',
                                'label' => 'Network Icon',
                                'name' => 'network_icon',
                                'type' => 'image',
                                'instructions' => 'Icon for the network, must be 24px square',
                                'column_width' => '',
                            ],
                            [
                                'default_value' => '',
                                'formatting' => 'none',
                                'key' => 'field_51b04ec7409ca',
                                'label' => 'Network Link',
                                'name' => 'network_link',
                                'type' => 'text',
                                'instructions' => 'External link to the social network.',
                                'column_width' => '',
                            ],
                        ],
                        'row_min' => 0,
                        'row_limit' => '',
                        'layout' => 'table',
                        'button_label' => 'Add Network',
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'acf-options-extra-options',
                            'order_no' => 0,
                            'group_no' => 0,
                        ],
                    ],
                ],
                'options' => [
                    'position' => 'normal',
                    'layout' => 'default',
                    'hide_on_screen' => [],
                ],
                'menu_order' => 12,
            ]);

            // Homepage Slider with Text
            acf_add_local_field_group([
                'key' => 'group_58c29b4871468',
                'title' => 'Homepage Slider with Text',
                'fields' => [
                    [
                        'key' => 'field_54c1681d2aec2',
                        'label' => 'Display type',
                        'name' => 'slider_display_type',
                        'type' => 'radio',
                        'choices' => [
                            'slider' => 'Slider',
                            'static' => 'Static',
                        ],
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'vertical',
                    ],
                    [
                        'key' => 'field_51c1b51130219',
                        'label' => 'Slider Images',
                        'name' => 'slider_images',
                        'type' => 'repeater',
                        'instructions' => 'Use this control to add images and text to the homepage. Top image should be 375px wide by 250px high. The other image should be 730px wide by 521px high.',
                        'sub_fields' => [
                            [
                                'save_format' => 'url',
                                'preview_size' => 'medium',
                                'library' => 'all',
                                'key' => 'field_51c1b5633021a',
                                'label' => 'Image',
                                'name' => 'image',
                                'type' => 'image',
                                'column_width' => '',
                            ],
                            [
                                'default_value' => '',
                                'formatting' => 'none',
                                'key' => 'field_51c1b5883021b',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'instructions' => 'Title that appears with the image above',
                                'column_width' => '',
                                'maxlength' => 60,
                            ],
                            [
                                'default_value' => '',
                                'formatting' => 'html',
                                'key' => 'field_51c1b5a33021c',
                                'label' => 'Body',
                                'name' => 'body',
                                'type' => 'textarea',
                                'instructions' => 'Body copy that appears with the image above',
                                'column_width' => '',
                                'maxlength' => 140,
                            ],
                            [
                                'post_type' => [
                                    0 => 'post',
                                    1 => 'page',
                                ],
                                'multiple' => 0,
                                'allow_null' => 0,
                                'key' => 'field_51c1bd4b12e4f',
                                'label' => 'Link',
                                'name' => 'link',
                                'type' => 'url',
                                'column_width' => '',
                            ],
                        ],
                        'row_min' => 0,
                        'row_limit' => '',
                        'layout' => 'row',
                        'button_label' => 'Add Slider Image',
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'page_template',
                            'operator' => '==',
                            'value' => 'page-home.php',
                            'order_no' => 0,
                            'group_no' => 0,
                        ],
                    ],
                ],
                'options' => [
                    'position' => 'normal',
                    'layout' => 'default',
                    'hide_on_screen' => [
                        0 => 'the_content',
                        1 => 'excerpt',
                        2 => 'custom_fields',
                    ],
                ],
                'menu_order' => 0,
            ]);

            // Category landing page
            acf_add_local_field_group([
                'key' => 'group_58c29baa4d49c',
                'title' => 'Category landing page',
                'fields' => [
                    [
                        'default_value' => '',
                        'key' => 'field_51f15a9975448',
                        'label' => 'Category ID',
                        'name' => 'category_id',
                        'type' => 'number',
                        'required' => 1,
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'page_template',
                            'operator' => '==',
                            'value' => 'page-category.php',
                            'order_no' => 0,
                            'group_no' => 0,
                        ],
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'page_template',
                            'operator' => '==',
                            'value' => 'page-blog.php',
                            'order_no' => 0,
                            'group_no' => 0,
                        ],
                    ],
                ],
                'options' => [
                    'position' => 'normal',
                    'layout' => 'no_box',
                    'hide_on_screen' => [],
                ],
                'menu_order' => 0,
            ]);

            // Descriptions for document search page
            acf_add_local_field_group([
                'key' => 'group_58c29bf7924d0',
                'title' => 'Descriptions for document search page',
                'fields' => [
                    [
                        'key' => 'field_52de88c61d4e2',
                        'label' => 'Search box',
                        'name' => 'search_box',
                        'type' => 'text',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_52de88f01d4e3',
                        'label' => 'Keywords',
                        'name' => 'keywords',
                        'type' => 'text',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_52de89041d4e4',
                        'label' => 'Proposed audience',
                        'name' => 'proposed_audience',
                        'type' => 'text',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_52de89541d4e5',
                        'label' => 'Directorate',
                        'name' => 'directorate',
                        'type' => 'text',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_52de895c1d4e6',
                        'label' => 'NHS Outcomes',
                        'name' => 'nhs_outcomes',
                        'type' => 'text',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_52de89681d4e7',
                        'label' => 'Product type',
                        'name' => 'product_type',
                        'type' => 'text',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_52de89701d4e8',
                        'label' => 'Subject area',
                        'name' => 'subject_area',
                        'type' => 'text',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'acf-options-extra-options',
                            'order_no' => 0,
                            'group_no' => 0,
                        ],
                    ],
                ],
                'options' => [
                    'position' => 'normal',
                    'layout' => 'default',
                    'hide_on_screen' => [],
                ],
                'menu_order' => 0,
            ]);

            // Section Landing Page
            acf_add_local_field_group([
                'key' => 'group_56700378568e6',
                'title' => 'Section landing page',
                'fields' => [
                    [
                        'key' => 'field_5670167086a6c',
                        'label' => 'Top Row',
                        'name' => 'top_row',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'min' => '',
                        'max' => 3,
                        'layout' => 'block',
                        'button_label' => 'Add Row',
                        'sub_fields' => [
                            [
                                'key' => 'field_56702806c1b0b',
                                'label' => 'URL',
                                'name' => 'url',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ],
                            [
                                'key' => 'field_5670281fc1b0c',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ],
                            [
                                'key' => 'field_5670282dc1b0d',
                                'label' => 'Excerpt',
                                'name' => 'excerpt',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => 'wpautop',
                                'readonly' => 0,
                                'disabled' => 0,
                            ],
                            [
                                'key' => 'field_56702834c1b0e',
                                'label' => 'Image',
                                'name' => 'image',
                                'type' => 'file',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'return_format' => 'url',
                                'library' => 'all',
                                'min_size' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ],
                        ],
                    ],
                    [
                        'key' => 'field_56702890749ed',
                        'label' => 'Bottom Row',
                        'name' => 'bottom_row',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'min' => '',
                        'max' => '',
                        'layout' => 'block',
                        'button_label' => 'Add Row',
                        'sub_fields' => [
                            [
                                'key' => 'field_5670289e749ee',
                                'label' => 'URL',
                                'name' => 'url',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ],
                            [
                                'key' => 'field_567028ad749ef',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ],
                            [
                                'key' => 'field_567028b6749f0',
                                'label' => 'Excerpt',
                                'name' => 'excerpt',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => 'wpautop',
                                'readonly' => 0,
                                'disabled' => 0,
                            ],
                            [
                                'key' => 'field_5757ebb14dcfa',
                                'label' => 'Image',
                                'name' => 'image',
                                'type' => 'file',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'return_format' => 'url',
                                'library' => 'all',
                                'min_size' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ],
                        ],
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'page_template',
                            'operator' => '==',
                            'value' => 'page-landing.php',
                        ],
                    ],
                ],
                'menu_order' => 1,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => 1,
                'description' => '',
            ]);

            // Also in this section
            acf_add_local_field_group([
                'key' => 'group_585a4daea0ff3',
                'title' => 'Also in this section',
                'fields' => [
                    [
                        'key' => 'field_585a4dc2d79c6',
                        'label' => 'Topics',
                        'name' => 'topics',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'collapsed' => '',
                        'min' => '',
                        'max' => '',
                        'layout' => 'row',
                        'button_label' => 'Add Topic',
                        'sub_fields' => [
                            [
                                'key' => 'field_585a4dfbd79c7',
                                'label' => 'Type',
                                'name' => 'type',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'choices' => [
                                    'Page' => 'Page',
                                    'Link' => 'Link',
                                ],
                                'allow_null' => 0,
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => 'Page',
                                'layout' => 'horizontal',
                                'return_format' => 'value',
                            ],
                            [
                                'key' => 'field_585a4ebdd79c8',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => [
                                    [
                                        [
                                            'field' => 'field_585a4dfbd79c7',
                                            'operator' => '==',
                                            'value' => 'Link',
                                        ],
                                    ],
                                ],
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ],
                            [
                                'key' => 'field_585a4f2fd79c9',
                                'label' => 'URL',
                                'name' => 'url',
                                'type' => 'url',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => [
                                    [
                                        [
                                            'field' => 'field_585a4dfbd79c7',
                                            'operator' => '==',
                                            'value' => 'Link',
                                        ],
                                    ],
                                ],
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => '',
                            ],
                            [
                                'key' => 'field_585a4facd79ca',
                                'label' => 'Page',
                                'name' => 'page',
                                'type' => 'post_object',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => [
                                    [
                                        [
                                            'field' => 'field_585a4dfbd79c7',
                                            'operator' => '==',
                                            'value' => 'Page',
                                        ],
                                    ],
                                ],
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'post_type' => [
                                    0 => 'page',
                                ],
                                'taxonomy' => [
                                ],
                                'allow_null' => 0,
                                'multiple' => 0,
                                'return_format' => 'object',
                                'ui' => 1,
                            ],
                        ],
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'page_template',
                            'operator' => '==',
                            'value' => 'page-landing.php',
                        ],
                    ],
                ],
                'menu_order' => 2,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => 1,
                'description' => '',
            ]);

            // Sidebar Links
            acf_add_local_field_group([
                'key' => 'group_685a4daea0ff4',
                'title' => 'Sidebar links',
                'fields' => [
                    [
                        'key' => 'field_68502806c1b0e',
                        'label' => 'Sidebar links title',
                        'name' => 'sidebar_links_title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ],
                    [
                        'key' => 'field_685a4dc2d79c7',
                        'label' => 'Topics',
                        'name' => 'sidebar_links_topics',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'collapsed' => '',
                        'min' => '',
                        'max' => '',
                        'layout' => 'row',
                        'button_label' => 'Add Topic',
                        'sub_fields' => [
                            [
                                'key' => 'field_6850289e749ef',
                                'label' => 'Link',
                                'name' => 'sidebar_links_url',
                                'type' => 'url',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                            ],
                            [
                                'key' => 'field_685028ad899ad',
                                'label' => 'Title',
                                'name' => 'sidebar_links_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ],
                        ],
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'post_template',
                            'operator' => '==',
                            'value' => 'page-home.php',
                        ],
                    ],
                ],
                'menu_order' => 3,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => 1,
                'description' => '',
            ]);
        }

        if (function_exists('acf_add_local_field_group')) {
            // Optional metadata
            acf_add_local_field_group([
                'key' => 'group_56672830553eb',
                'title' => 'Optional metadata',
                'fields' => [
                    [
                        'key' => 'field_566728599cda1',
                        'label' => 'Owner',
                        'name' => 'owner',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ],
                    [
                        'key' => 'field_566728839cda2',
                        'label' => 'Description',
                        'name' => 'description',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => 'wpautop',
                        'readonly' => 0,
                        'disabled' => 0,
                    ],
                    [
                        'key' => 'field_566728919cda3',
                        'label' => 'Gateway Ref',
                        'name' => 'gateway_ref',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ],
                    [
                        'key' => 'field_5667289b9cda4',
                        'label' => 'PCC Reference',
                        'name' => 'pcc_reference',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'post',
                        ],
                    ],
                    [
                        [
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'page',
                        ],
                    ],
                    [
                        [
                            'param' => 'attachment',
                            'operator' => '==',
                            'value' => 'all',
                        ],
                    ],
                    [
                        [
                            'param' => 'page_template',
                            'operator' => '!==',
                            'value' => 'page-landing.php',
                        ],
                    ],
                ],
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'seamless',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => 1,
                'description' => '',
            ]);
        }

        if (function_exists('acf_add_local_field_group')) {
            // News Sidebar
            acf_add_local_field_group([
                'key' => 'group_57f7634dda372',
                'title' => 'News Sidebar',
                'fields' => [
                    [
                        'key' => 'field_57f7636cb91cf',
                        'label' => 'News Items',
                        'name' => 'news_items',
                        'type' => 'taxonomy',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'taxonomy' => 'category',
                        'field_type' => 'select',
                        'allow_null' => 0,
                        'add_term' => 0,
                        'save_terms' => 0,
                        'load_terms' => 0,
                        'return_format' => 'id',
                        'multiple' => 0,
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'page_template',
                            'operator' => '==',
                            'value' => 'page-landing.php',
                        ],
                    ],
                ],
                'menu_order' => 1,
                'position' => 'side',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => 1,
                'description' => '',
            ]);

            acf_add_local_field_group([
                'key' => 'group_58c179a3ac3a8',
                'title' => 'Publication container banner',
                'fields' => [
                    [
                        'default_value' => 0,
                        'message' => '',
                        'ui' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                        'key' => 'field_58c179bae4dc5',
                        'label' => 'Show publication container beta banner',
                        'name' => 'show_publication_container_beta_banner',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'key' => 'field_58c179dde4dc6',
                        'label' => 'Publication banner beta text',
                        'name' => 'publication_banner_beta_text',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'acf-options-extra-options',
                        ],
                    ],
                ],
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => 1,
                'description' => '',
            ]);

            acf_add_local_field_group([
                'key' => 'group_58c179a3ac3h3',
                'title' => 'News homepage banner',
                'fields' => [
                    [
                        'default_value' => 0,
                        'message' => '',
                        'ui' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                        'key' => 'field_58c179bae4dh2',
                        'label' => 'Show news homepage banner',
                        'name' => 'show_news_homepage_banner',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'key' => 'field_58c179dde4dh1',
                        'label' => 'News homepage banner text',
                        'name' => 'news_homepage_banner_text',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'acf-options-extra-options',
                        ],
                    ],
                ],
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => 1,
                'description' => '',
            ]);
        }
    }
}
