<?php

namespace NHSEngland;

use Dxw\Iguana\Registerable;

class LandingPageFields implements Registerable
{
    const TEMPLATE = 'page-landing-new.php';

    public function register()
    {
        add_action('init', [$this, 'addFields']);
    }

    public function addFields()
    {
        if (!function_exists('acf_add_local_field_group')) {
            return;
        }

        acf_add_local_field_group([
            'key' => 'group_582c7203ee0b6',
            'title' => 'Content blocks',
            'fields' => [
                [
                    'key' => 'field_582c72162a32b',
                    'label' => 'Blocks',
                    'name' => 'blocks',
                    'type' => 'flexible_content',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'button_label' => 'Add block',
                    'min' => '',
                    'max' => '',
                    'layouts' => [
                        // Video Block
                        [
                            'key' => '582c723018bb3',
                            'name' => 'video',
                            'label' => 'Video',
                            'display' => 'row',
                            'sub_fields' => [
                                [
                                    'key' => 'field_582c72482a32c',
                                    'label' => 'YouTube link',
                                    'name' => 'youtube_link',
                                    'type' => 'url',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => '',
                                    'placeholder' => 'https://www.youtube.com/watch?v=IIGsy93ai94',
                                ],
                                [
                                    'key' => 'field_582c911fc7888',
                                    'label' => 'Video title',
                                    'name' => 'video_title',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ],
                                [
                                    'key' => 'field_582c74552a32e',
                                    'label' => 'Content',
                                    'name' => 'content',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                ],
                                [
                                    'key' => 'field_582dc5c7a8a33',
                                    'label' => 'Include call to action',
                                    'name' => 'include_call_to_action',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'message' => '',
                                    'default_value' => 0,
                                ],
                                [
                                    'key' => 'field_582dc5dea8a34',
                                    'label' => 'Call to action text',
                                    'name' => 'call_to_action_text',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => [
                                        [
                                            [
                                                'field' => 'field_582dc5c7a8a33',
                                                'operator' => '==',
                                                'value' => '1',
                                            ],
                                        ],
                                    ],
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ],
                                [
                                    'key' => 'field_582dc5eaa8a35',
                                    'label' => 'Call to action link',
                                    'name' => 'call_to_action_link',
                                    'type' => 'url',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => [
                                        [
                                            [
                                                'field' => 'field_582dc5c7a8a33',
                                                'operator' => '==',
                                                'value' => '1',
                                            ],
                                        ],
                                    ],
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => '',
                                    'placeholder' => '',
                                ],
                            ],
                            'min' => '',
                            'max' => '',
                        ],
                        // Latest Posts
                        [
                            'key' => '582c73052a32d',
                            'name' => 'latest_posts',
                            'label' => 'Latest posts',
                            'display' => 'row',
                            'sub_fields' => [
                                [
                                    'key' => 'field_582c79b1ccda7',
                                    'label' => 'Section title',
                                    'name' => 'section_title',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => '',
                                    'placeholder' => 'eg. Recent blog posts',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ],
                                [
                                    'key' => 'field_582c75752a330',
                                    'label' => 'Number of posts',
                                    'name' => 'number_of_posts',
                                    'type' => 'number',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => 4,
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'min' => '',
                                    'max' => '',
                                    'step' => '',
                                ],
                                [
                                    'key' => 'field_582c74e52a32f',
                                    'label' => 'Select category',
                                    'name' => 'select_category',
                                    'type' => 'taxonomy',
                                    'instructions' => '(Leave blank for all categories)',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'taxonomy' => 'category',
                                    'field_type' => 'multi_select',
                                    'allow_null' => 0,
                                    'add_term' => 1,
                                    'save_terms' => 0,
                                    'load_terms' => 0,
                                    'return_format' => 'id',
                                    'multiple' => 0,
                                ],
                                [
                                    'key' => 'field_582dc580a8a32',
                                    'label' => 'Include call to action',
                                    'name' => 'include_call_to_action',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'message' => '',
                                    'default_value' => 0,
                                ],
                                [
                                    'key' => 'field_582dc533a8a2f',
                                    'label' => 'Call to action text',
                                    'name' => 'call_to_action_text',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => [
                                        [
                                            [
                                                'field' => 'field_582dc580a8a32',
                                                'operator' => '==',
                                                'value' => '1',
                                            ],
                                        ],
                                    ],
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ],
                                [
                                    'key' => 'field_582dc546a8a30',
                                    'label' => 'Call to action link',
                                    'name' => 'call_to_action_link',
                                    'type' => 'url',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => [
                                        [
                                            [
                                                'field' => 'field_582dc580a8a32',
                                                'operator' => '==',
                                                'value' => '1',
                                            ],
                                        ],
                                    ],
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => '',
                                    'placeholder' => '',
                                ],
                                [
                                    'key' => 'field_59550d7b3525a',
                                    'label' => 'Background?',
                                    'name' => 'background',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'message' => '',
                                    'default_value' => 0,
                                    'ui' => 0,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                ],
                                [
                                    'key' => 'field_59550d9b3525b',
                                    'label' => 'Background colour',
                                    'name' => 'background_colour',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => [
                                        [
                                            [
                                                'field' => 'field_59550d7b3525a',
                                                'operator' => '==',
                                                'value' => '1',
                                            ],
                                        ],
                                    ],
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => '',
                                ],
                            ],
                            'min' => '',
                            'max' => '',
                        ],
                        // Document
                        [
                            'key' => '582c760c2a332',
                            'name' => 'document',
                            'label' => 'Document',
                            'display' => 'row',
                            'sub_fields' => [
                                [
                                    'key' => 'field_582c76452a333',
                                    'label' => 'File',
                                    'name' => 'file',
                                    'type' => 'post_object',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'post_type' => [
                                        0 => 'attachment',
                                    ],
                                    'taxonomy' => [
                                    ],
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'return_format' => 'object',
                                    'ui' => 1,
                                ],
                                [
                                    'key' => 'field_582cd5cb2b9f0',
                                    'label' => 'Document title',
                                    'name' => 'document_title',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ],
                                [
                                    'key' => 'field_582cd6142b9f1',
                                    'label' => 'Description',
                                    'name' => 'description',
                                    'type' => 'textarea',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'maxlength' => '',
                                    'rows' => '',
                                    'new_lines' => 'wpautop',
                                ],
                                [
                                    'key' => 'field_582dc603a8a36',
                                    'label' => 'Include call to action',
                                    'name' => 'include_call_to_action',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'message' => '',
                                    'default_value' => 0,
                                ],
                                [
                                    'key' => 'field_582dc613a8a37',
                                    'label' => 'Call to action text',
                                    'name' => 'call_to_action_text',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => [
                                        [
                                            [
                                                'field' => 'field_582dc603a8a36',
                                                'operator' => '==',
                                                'value' => '1',
                                            ],
                                        ],
                                    ],
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ],
                                [
                                    'key' => 'field_582dc642a8a38',
                                    'label' => 'Call to action link',
                                    'name' => 'call_to_action_link',
                                    'type' => 'url',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => [
                                        [
                                            [
                                                'field' => 'field_582dc603a8a36',
                                                'operator' => '==',
                                                'value' => '1',
                                            ],
                                        ],
                                    ],
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => '',
                                    'placeholder' => '',
                                ],
                            ],
                            'min' => '',
                            'max' => '',
                        ],
                    ],
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => static::TEMPLATE,
                    ],
                ],
            ],
            'menu_order' => 4,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => [
                0 => 'the_content',
            ],
            'active' => 1,
            'description' => '',
        ]);

        acf_add_local_field_group([
            'key' => 'group_5832d4f8357d7',
            'title' => 'In this section',
            'fields' => [
                [
                    'key' => 'field_5832d501a00fc',
                    'label' => 'Topics',
                    'name' => 'topics',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'collapsed' => '',
                    'min' => '',
                    'max' => '',
                    'layout' => 'row',
                    'button_label' => 'Add Topic',
                    'sub_fields' => [
                        [
                            'key' => 'field_5832d7951393a',
                            'label' => 'Type',
                            'name' => 'type',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'choices' => [
                                'Page' => 'Page',
                                'Link' => 'Link',
                            ],
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'default_value' => 'Page',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                        ],
                        [
                            'key' => 'field_5832d516a00fd',
                            'label' => 'Title',
                            'name' => 'title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => [
                                [
                                    [
                                        'field' => 'field_5832d7951393a',
                                        'operator' => '==',
                                        'value' => 'Link',
                                    ],
                                ],
                            ],
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ],
                        [
                            'key' => 'field_5832d530a00fe',
                            'label' => 'URL',
                            'name' => 'url',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => [
                                [
                                    [
                                        'field' => 'field_5832d7951393a',
                                        'operator' => '==',
                                        'value' => 'Link',
                                    ],
                                ],
                            ],
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => '',
                            'placeholder' => '',
                        ],
                        [
                            'key' => 'field_5832d7e21393b',
                            'label' => 'Page',
                            'name' => 'page',
                            'type' => 'post_object',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => [
                                [
                                    [
                                        'field' => 'field_5832d7951393a',
                                        'operator' => '==',
                                        'value' => 'Page',
                                    ],
                                ],
                            ],
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'post_type' => [
                                0 => 'page',
                            ],
                            'taxonomy' => [
                            ],
                            'allow_null' => 0,
                            'multiple' => 0,
                            'return_format' => 'object',
                            'ui' => 1,
                        ],
                    ],
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => static::TEMPLATE,
                    ],
                ],
            ],
            'menu_order' => 3,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ]);

        acf_add_local_field_group([
            'key' => 'group_582c4426eb177',
            'title' => 'Hero unit',
            'fields' => [
                [
                    'key' => 'field_582c7ad5ccf73',
                    'label' => 'Use page title',
                    'name' => 'use_page_title',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'message' => '',
                    'default_value' => 1,
                ],
                [
                    'key' => 'field_582c443792d04',
                    'label' => 'Title',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => [
                        [
                            [
                                'field' => 'field_582c7ad5ccf73',
                                'operator' => '!=',
                                'value' => '1',
                            ],
                        ],
                    ],
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ],
                [
                    'key' => 'field_582c4da1e6db4',
                    'label' => 'Section',
                    'name' => 'section',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => 'eg. Our Work',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ],
                [
                    'key' => 'field_582c44d792d05',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => 6,
                    'new_lines' => 'wpautop',
                ],
                [
                    'key' => 'field_582c450292d06',
                    'label' => 'Background image',
                    'name' => 'background_image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'return_format' => 'url',
                    'preview_size' => 'full',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => 'jpg,jpeg,png,gif',
                ],
                [
                    'key' => 'field_582c455092d07',
                    'label' => 'Background scroll',
                    'name' => 'background_scroll',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'choices' => [
                        'None' => 'None',
                        'Fixed' => 'Fixed',
                        'Parallax' => 'Parallax',
                    ],
                    'default_value' => [
                        0 => 'None',
                    ],
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ],
                [
                    'key' => 'field_582eefdb061ac',
                    'label' => 'White background behind text',
                    'name' => 'white_background_behind_text',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'message' => '',
                    'default_value' => 0,
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => static::TEMPLATE,
                    ],
                ],
            ],
            'menu_order' => 1,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'left',
            'instruction_placement' => 'label',
            'hide_on_screen' => [
                0 => 'the_content',
                1 => 'custom_fields',
                2 => 'discussion',
                3 => 'comments',
                4 => 'revisions',
                5 => 'slug',
                6 => 'author',
                7 => 'format',
                8 => 'featured_image',
                9 => 'send-trackbacks',
            ],
            'active' => 1,
            'description' => '',
        ]);

        acf_add_local_field_group([
            'key' => 'group_582c4eaa49cac',
            'title' => 'Main links',
            'fields' => [
                [
                    'key' => 'field_582c4ebbc3383',
                    'label' => 'Links',
                    'name' => 'links',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'collapsed' => '',
                    'min' => '',
                    'max' => '',
                    'layout' => 'row',
                    'button_label' => 'Add link',
                    'sub_fields' => [
                        [
                            'key' => 'field_582c4ee5c3384',
                            'label' => 'Title',
                            'name' => 'title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ],
                        [
                            'key' => 'field_582c4f12c3385',
                            'label' => 'URL',
                            'name' => 'url',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => '',
                            'placeholder' => '',
                        ],
                        [
                            'key' => 'field_582c4f31c3386',
                            'label' => 'Body',
                            'name' => 'body',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 6,
                            'new_lines' => 'wpautop',
                        ],
                    ],
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => static::TEMPLATE,
                    ],
                ],
            ],
            'menu_order' => 2,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ]);
    }
}
